  grafana:
    image: grafana/grafana:${grafana_version}
    ports:
      - "8080:8080"
    volumes:
      - "./dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml"
      - "./dev-dashboards:/usr/share/grafana/devenv/dev-dashboards"
      - "./datasources_docker.yaml:/etc/grafana/provisioning/datasources/datasources.yaml"
    environment:
      GF_RENDERING_SERVER_URL: http://renderer:8081/render
      GF_RENDERING_CALLBACK_URL: http://grafana:8080/

  renderer:
    image: grafana/grafana-image-renderer:latest
